### ISSUE TITLE
Review Notes

### ISSUE THREAD

**Issue by tallaxes** [hotforfeature/angular-polymer-sink#1]
# General

- Nice trick with conditional waiting for `WebComponentsReady`, is that standard practice?
- Like that all mechanisms (`polymer` attribute directive, `@PolymerProperty`,  library selectors) let one choose between not using the capabilities at all, enabling explicitly or enabling implicitly
- Styling is not addressed, right? May be a good idea to keep a list of potential integration issues that the library does not address in the documentation.

# Two-way databinding
- Couldn't `polymer` attribute do event structure translation as well, making `@PolymerProperty` unnecessary? That's what the original angular-polymer does, [here](https://github.com/platosha/angular-polymer/blob/master/src/polymer-element.ts#L129). There are tradeoffs …
- I noticed it uses `nativeElement.dispatchEvent(new CustomEvent(…))`, where the original angular-polymer used `EventEmitter`. What are the reasons for and implications of the difference?
- `PolymerProperty.unwrap` (and `@PolymerProperty` decorator that uses it) should and does pass through anything that is not `CustomEvent`; may be a good idea to make this clear in the documentation.
- Not 100% sure the names for `polymer` attribute directive and `@PolymerProperty` decorator are perfect, but don't have a better suggestion

# Change Detection
- It was not clear to me (until I looked at the code) that what makes `OnPolymerChange` work is the setter from `@PolymerProperty`; may be a good idea to make this clear in the documentation

# Forms
- Don't yet understand it well enough to comment (though a use of `ironControl` attribute directive to surface the functionality makes sense)

# Polymer Templates
- Good explanation; the actual support (`polymer-template`) is only needed until Angular fixes the flag, right?

**Comment by hotforfeature** [comment]
I'll try to answer everything, good points @tallaxes!

## General

#### `WebComponentsReady`

My thing of setting a boolean flag is not really standard. Most apps just need to wrap themselves in an event listener since loader dispatches the event on a request animation frame. However, Angular CLI projects add the bundle as `<script src="main.bundle.js" async>`, so the bundle actually loads after the RAF and event fire. [I made an issue](https://github.com/webcomponents/webcomponentsjs/issues/746) for it, but the workaround is pretty easy.

#### Style

Not addressed yet, and good point about keeping track of features! I'm pulling the library into its own repo that I'll be publishing shortly. It has a readme with support and going to support features 👍 

## Two-way databinding

#### EventEmitter

The first two points kind of relate to each other. Angular listens for `propertyChange` as either an Event dispatched by the component, or a subscribe-able `@Output()` property named `propertyChange`.

I thought about just adding the properties to either the custom element or the `[polymer]` directive at runtime. The big catch is that in order for Angular to know about an EventEmitter, it must be decorated as an `@Output()`. So we can't just add a `disabledChange` EventEmitter property to the `[polymer]` directive or custom element and cross our fingers that it works. 

We can register EventEmitters dynamically as outputs at runtime by creating the directive dynamically. This is what `angular-polymer` does, but the downside is we lose AoT support.

The tl;dr; is all about supporting AoT.

#### PolymerProperty.unwrap()

Good point! The docs should indicate that it's very forgiving and non-destructive. Developers shouldn't wonder if they need to check if the value is a CustomEvent before they use it.

#### Naming

I don't feel like they're perfect either 😢 . I'm open to brainstorming more semantic names.

## Change Detection

👍  for clearer documentation.

## Forms

They're hella complicated. A lot of my form experience actually came from working with Ionic, and specifically how they deal with `NgControl` on their [input](https://github.com/driftyco/ionic/blob/master/src/components/input/input.ts) component.

## Polymer Templates

Correct. As soon as https://github.com/angular/angular/issues/15555 and https://github.com/angular/angular/issues/15557 are resolved, `polymer-template` can be deprecated.

**Comment by tallaxes** [comment]
> At the moment there is no build tool like vulcanize to concatenate all imports into a single HTML file.

Didn't vulcanize become [polymer-bundler](https://github.com/Polymer/polymer-bundler) in Polymer 2+? (Have not used either in Angular context ...)

**Comment by hotforfeature** [comment]
This library has migrated to [Origami](https://github.com/hotforfeature/origami) and the remaining review notes that have not been implemented were added to the [1.0.0 milestone](https://github.com/hotforfeature/origami/milestone/1).
